name: ${project.name}
version: ${project.version}-${git.commit.id.abbrev}
description: ${project.description}
author: ${bukkit.plugin.authors}
website: ${project.url}
main: ${bukkit.plugin.main}
depend: [ProtocolLib]
commands:
  heads:
    permission: headdictionary.use
